# Generated by Django 2.0.6 on 2021-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='商品代码')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('alias', models.CharField(max_length=50, verbose_name='别名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='价格')),
                ('units', models.IntegerField(verbose_name='单位')),
                ('counter', models.IntegerField(verbose_name='库存')),
                ('sale_counter', models.IntegerField(verbose_name='累计销量')),
            ],
        ),
    ]
