# Generated by Django 2.0.6 on 2021-02-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210227_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='counter',
            field=models.IntegerField(default=0, null=True, verbose_name='数量'),
        ),
    ]
